spring:
  application:
    name: pgsql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.111.52:5432/assess_standard_tool
      username: postgres
      password: Y4yhl9tbf120
      min-idle: 10
      max-active: 70
      initial-size: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
